export const genres = {
  0: "pop",
  1: "rock",
  2: "jazz",
  3: "country",
  4: "hip-hop",
  5: "r&b",
  6: "reggae",
  7: "blues",
  8: "gospel",
  9: "classical",
  10: "metal",
  11: "electronic",
  12: "folk",
  13: "punk",
  14: "alternative",
  15: "indie",
  16: "dance",
};
